### ISSUE TITLE
" AttributeError: 'str' object has no attribute 'get' " while attaching a volume to the instance using server_add_volume

### ISSUE THREAD

**Issue by radesai3** [RedHatQE/teflo_openstack_client_plugin#12]
**While attaching a volume to the instance using server_add_volume, got the below error**

File "/home/user/teflo/lib/python3.6/site-packages/teflo_openstack_client_plugin/helpers/os_client_helper.py", line 132, in parse_network_addresses_to_dict
    if json_resp.get('addresses', {}):
AttributeError: 'str' object has no attribute 'get'

**The content of the scenario.yml file is**
```
provision:
  - name: test_voll
    provisioner: openstack-client
    volume:
      size: 5
    credential: openstack

  - name: teflo_clit
    groups: client, test_driver
    provisioner: openstack-client
    credential: openstack
    server:
      key_name: os
      image: RHEL-8.5.0-x86_64-released
      flavor: m1.small
      network:
        - provider_net_cci_8
    server_add_volume:
      - device: /dev/vdb
        tgt_res: test_voll
      
    ansible_params:
      ansible_user: cloud-user
      ansible_ssh_private_key_file:  keys/keys
```

**The volumes are attached to the instances but the result is failed and the above error is displayed**
